version: '3.8'

services:
  wordpress:
    image: wordpress
    ports:
      - "82:80"
    networks:
      - redDocker
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress

  mariadb:
    image: mariadb
    networks:
      - redDocker
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

networks:
  redDocker:

volumes:
  wordpress_data:
  mariadb_data: